<?php
/**
 * IfcMerge
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BIMData API
 *
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@bimdata.io
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * IfcMerge Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class IfcMerge implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'IfcMerge';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'ifc_ids' => 'int[]',
        'floating_point_reduction' => 'int',
        'export_name' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'ifc_ids' => null,
        'floating_point_reduction' => null,
        'export_name' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'ifc_ids' => 'ifc_ids',
        'floating_point_reduction' => 'floating_point_reduction',
        'export_name' => 'export_name'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'ifc_ids' => 'setIfcIds',
        'floating_point_reduction' => 'setFloatingPointReduction',
        'export_name' => 'setExportName'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'ifc_ids' => 'getIfcIds',
        'floating_point_reduction' => 'getFloatingPointReduction',
        'export_name' => 'getExportName'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['ifc_ids'] = $data['ifc_ids'] ?? null;
        $this->container['floating_point_reduction'] = $data['floating_point_reduction'] ?? null;
        $this->container['export_name'] = $data['export_name'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['ifc_ids'] === null) {
            $invalidProperties[] = "'ifc_ids' can't be null";
        }
        if ((count($this->container['ifc_ids']) < 2)) {
            $invalidProperties[] = "invalid value for 'ifc_ids', number of items must be greater than or equal to 2.";
        }

        if (!is_null($this->container['floating_point_reduction']) && ($this->container['floating_point_reduction'] > 15)) {
            $invalidProperties[] = "invalid value for 'floating_point_reduction', must be smaller than or equal to 15.";
        }

        if (!is_null($this->container['floating_point_reduction']) && ($this->container['floating_point_reduction'] < 6)) {
            $invalidProperties[] = "invalid value for 'floating_point_reduction', must be bigger than or equal to 6.";
        }

        if ($this->container['export_name'] === null) {
            $invalidProperties[] = "'export_name' can't be null";
        }
        if ((mb_strlen($this->container['export_name']) > 512)) {
            $invalidProperties[] = "invalid value for 'export_name', the character length must be smaller than or equal to 512.";
        }

        if ((mb_strlen($this->container['export_name']) < 1)) {
            $invalidProperties[] = "invalid value for 'export_name', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets ifc_ids
     *
     * @return int[]
     */
    public function getIfcIds()
    {
        return $this->container['ifc_ids'];
    }

    /**
     * Sets ifc_ids
     *
     * @param int[] $ifc_ids ifc_ids
     *
     * @return self
     */
    public function setIfcIds($ifc_ids)
    {


        if ((count($ifc_ids) < 2)) {
            throw new \InvalidArgumentException('invalid length for $ifc_ids when calling IfcMerge., number of items must be greater than or equal to 2.');
        }
        $this->container['ifc_ids'] = $ifc_ids;

        return $this;
    }

    /**
     * Gets floating_point_reduction
     *
     * @return int|null
     */
    public function getFloatingPointReduction()
    {
        return $this->container['floating_point_reduction'];
    }

    /**
     * Sets floating_point_reduction
     *
     * @param int|null $floating_point_reduction Precision of geometries. 6 is micrometre, 9 is nanometre, ect...
     *
     * @return self
     */
    public function setFloatingPointReduction($floating_point_reduction)
    {

        if (!is_null($floating_point_reduction) && ($floating_point_reduction > 15)) {
            throw new \InvalidArgumentException('invalid value for $floating_point_reduction when calling IfcMerge., must be smaller than or equal to 15.');
        }
        if (!is_null($floating_point_reduction) && ($floating_point_reduction < 6)) {
            throw new \InvalidArgumentException('invalid value for $floating_point_reduction when calling IfcMerge., must be bigger than or equal to 6.');
        }

        $this->container['floating_point_reduction'] = $floating_point_reduction;

        return $this;
    }

    /**
     * Gets export_name
     *
     * @return string
     */
    public function getExportName()
    {
        return $this->container['export_name'];
    }

    /**
     * Sets export_name
     *
     * @param string $export_name export_name
     *
     * @return self
     */
    public function setExportName($export_name)
    {
        if ((mb_strlen($export_name) > 512)) {
            throw new \InvalidArgumentException('invalid length for $export_name when calling IfcMerge., must be smaller than or equal to 512.');
        }
        if ((mb_strlen($export_name) < 1)) {
            throw new \InvalidArgumentException('invalid length for $export_name when calling IfcMerge., must be bigger than or equal to 1.');
        }

        $this->container['export_name'] = $export_name;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


